parameters:
    mucho_mas_facil_file_manager.options:
        default:
            upload_path_after_document_root: /uploads/
            create_path_if_not_exist: true
            replace_old_file: false
            max_number_of_files: 10  # ~ means any number of files
            on_select_callback_function:  ~
            size_limit:  204800 #in bytes
            allowed_extensions:  jpg,jpeg,png,gif  # ~ means any extension #should go like : [ext: mimetype, jpg: [image/jpeg, image/pjpeg], ]
            allowed_roles:  ROLE_USER, ROLE_ADMIN # ~means any user
        single_image:
            upload_path_after_document_root: /uploads/images/
            max_number_of_files: 1
        single_any_file:
            upload_path_after_document_root: /uploads/files/
            max_number_of_files: 1
            allowed_extensions: ~
        single_pdf:
            upload_path_after_document_root: /uploads/pdf/
            max_number_of_files: 1
            allowed_extensions: pdf
        collection_image:
            upload_path_after_document_root: /uploads/images/
            max_number_of_files: ~
        collection_swf:
            upload_path_after_document_root: /uploads/swf/
            max_number_of_files: ~
            allowed_extensions: swf
        collection_any_file:
            upload_path_after_document_root: /uploads/files/
            max_number_of_files: ~
            allowed_extensions: ~
        collection_10_pdf:
            upload_path_after_document_root: /uploads/pdf/
            max_number_of_files: 10
            allowed_extensions: pdf

services:
#    mucho_mas_facil_file_manager.example:
#        class: %mucho_mas_facil_file_manager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

