parameters:
    mucho_mas_facil_file_manager.options:
        options:
            default:
                upload_path_after_document_root: /uploads/
                create_path_if_not_exist: true
                replace_old_file: false
                max_number_of_files: 10  # ~ means any number of files
                on_select_callback_function:  ~
                allowed_roles:  ROLE_USER, ROLE_ADMIN # ~means any user
                allowed_extensions:  'jpg', 'jpeg', 'png', 'gif'  # ~ means any extension
                size_limit:  204800
                min_size_limit:  ~
                max_connections:  3
                #thumnails:  null use avalancheimaginebundle instead
                #ckeditorfuncnum:  null
                #ckeditor:  null
                #langcode:  null
            single_image:
                max_number_of_files: 1
            single_pdf:
                max_number_of_files: 1
                allowed_extensions: 'pdf'
            single_any_file:
                max_number_of_files: 1
                allowed_extensions: ~
            collection_image:
                max_number_of_files: ~
            collection_swf:
                max_number_of_files: ~
                allowed_extensions: 'swf'
            collection_any_file:
                max_number_of_files: ~
                allowed_extensions: ~

services:
#    mucho_mas_facil_file_manager.example:
#        class: %mucho_mas_facil_file_manager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

